#!/bin/bash
### BEGIN INIT INFO
# Provides:          mxcamera
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mxCamera service
# Description:       Real-time camera display system
### END INIT INFO

DAEMON_PATH="/root/Workspace"
DAEMON="mxCamera"
DAEMON_ARGS="--width 1920 --height 1080"
PIDFILE="/var/run/mxcamera.pid"

case "$1" in
start)
    echo "Starting $DAEMON..."
    cd $DAEMON_PATH
    nohup ./$DAEMON $DAEMON_ARGS > /var/log/mxcamera.log 2>&1 & echo $! > $PIDFILE
    ;;
stop)
    echo "Stopping $DAEMON..."
    if [ -f $PIDFILE ]; then
        kill `cat $PIDFILE`
        rm $PIDFILE
    fi
    ;;
restart)
    $0 stop
    sleep 2
    $0 start
    ;;
status)
    if [ -f $PIDFILE ]; then
        echo "$DAEMON is running (PID: `cat $PIDFILE`)"
    else
        echo "$DAEMON is not running"
    fi
    ;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0